version: '3'
services:
  sonar-5:
    image: sonarqube:5.6.6-alpine
    hostname: sonar-5
    ports:
      - 9500:9000
    networks:
      - sonarnet
  sonar-6.0:
    image: sonarqube:6.0-alpine
    ports:
      - 9600:9000
    networks:
      - sonarnet
  sonar-6.5:
    image: sonarqube:6.5-alpine
    ports:
      - 9605:9000
    networks:
      - sonarnet
  jenkins-lts:
    image: jenkins/jenkins:lts-alpine
    environment:
      - JAVA_OPTS=-Dhudson.model.ParametersAction.keepUndefinedParameters=true
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - jenkins-lts-data:/var/jenkins_home
    networks:
      - sonarnet
  jenkins:
    image: jenkins/jenkins:alpine
    environment:
      - JAVA_OPTS=-Dhudson.model.ParametersAction.keepUndefinedParameters=true
    ports:
      - 8889:8080
      - 50001:50000
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - sonarnet

volumes:
  jenkins-lts-data:
  jenkins-data:

networks:
  sonarnet:
