version: '2'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-custom-db
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
    volumes:
      - mysql-data:/var/jenkins_home
    networks:
      - desenvnet
    mem_limit: 256M
  sonar-5:
    image: sonarqube:5.6.6-alpine
    hostname: sonar-5
    ports:
      - 9500:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar_5?useUnicode=true&characterEncoding=utf8
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=senha123
    links:
      - mysql:mysql
    networks:
      - desenvnet
    mem_limit: 1024M
  sonar-6.0:
    image: sonarqube:6.0-alpine
    hostname: sonar-6.0
    ports:
      - 9600:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar_6_0?useUnicode=true&characterEncoding=utf8
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=senha123
    links:
      - mysql:mysql
    networks:
      - desenvnet
    mem_limit: 1024M
  sonar-6.4:
    image: sonarqube:6.4-alpine
    hostname: sonar-6.4
    ports:
      - 9604:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar_6_4?useUnicode=true&characterEncoding=utf8
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=senha123
    links:
      - mysql:mysql
    networks:
      - desenvnet
    mem_limit: 1024M
  jenkins-lts:
    image: jenkins:alpine
    hostname: jenkins-lts
    environment:
      - JAVA_OPTS=-Dhudson.model.ParametersAction.keepUndefinedParameters=true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-lts-data:/var/jenkins_home
    links:
      - sonar-5
      - sonar-6.0
      - sonar-6.4
    networks:
      - desenvnet
    mem_limit: 2048M

volumes:
  mysql-data:
  jenkins-lts-data:

networks:
  desenvnet:
